import type { Prisma } from "../src/generated/prisma/client";

/** Platform-wide starter items (organizationId null). Idempotent via count check in seed. */
export const GLOBAL_QUESTION_BANK_SEED: Prisma.QuestionBankItemCreateManyInput[] = [
  {
    organizationId: null,
    framework: "IB",
    subject: "Mathematics",
    gradeLabel: "DP AA SL",
    standardCode: "N&S-1.1",
    type: "MCQ",
    prompt: "Which expression is equivalent to (x³)²?",
    points: 1,
    options: {
      choices: [
        { id: "a", text: "x⁵", correct: false },
        { id: "b", text: "x⁶", correct: true },
        { id: "c", text: "2x³", correct: false },
        { id: "d", text: "x⁹", correct: false },
      ],
    },
  },
  {
    organizationId: null,
    framework: "IB",
    subject: "Mathematics",
    gradeLabel: "DP AI HL",
    standardCode: "F&C-2.3",
    type: "TRUE_FALSE",
    prompt: "The derivative of a constant function is always zero.",
    points: 1,
    correctAnswer: "true",
  },
  {
    organizationId: null,
    framework: "IB",
    subject: "Physics",
    gradeLabel: "DP SL",
    standardCode: "A.1",
    type: "MCQ",
    prompt: "Which quantity is a vector?",
    points: 1,
    options: {
      choices: [
        { id: "a", text: "Speed", correct: false },
        { id: "b", text: "Displacement", correct: true },
        { id: "c", text: "Distance", correct: false },
        { id: "d", text: "Energy", correct: false },
      ],
    },
  },
  {
    organizationId: null,
    framework: "IB",
    subject: "English",
    gradeLabel: "DP HL",
    standardCode: "LIT-4",
    type: "SHORT_ANSWER",
    prompt: "What literary device uses 'like' or 'as' to compare two things?",
    points: 1,
    correctAnswer: "simile",
  },
  {
    organizationId: null,
    framework: "IB",
    subject: "Biology",
    gradeLabel: "DP SL",
    standardCode: "B.2",
    type: "LONG_ANSWER",
    prompt: "Explain the role of enzymes in lowering activation energy in one short paragraph.",
    points: 3,
    markingScheme:
      "2–3 pts: mentions catalyst, specific binding, transition state or activation energy. 1 pt: partial or vague. 0: incorrect.",
  },
  {
    organizationId: null,
    framework: "IB",
    subject: "Chemistry",
    gradeLabel: "DP SL",
    standardCode: "C.1",
    type: "TRUE_FALSE",
    prompt: "Isotopes of an element have the same number of protons.",
    points: 1,
    correctAnswer: "true",
  },
  {
    organizationId: null,
    framework: "IB",
    subject: "Economics",
    gradeLabel: "DP SL",
    standardCode: "E.3",
    type: "MCQ",
    prompt: "When demand increases and supply is unchanged, ceteris paribus, equilibrium price will:",
    points: 1,
    options: {
      choices: [
        { id: "a", text: "Fall", correct: false },
        { id: "b", text: "Rise", correct: true },
        { id: "c", text: "Stay the same", correct: false },
        { id: "d", text: "Become undefined", correct: false },
      ],
    },
  },
  {
    organizationId: null,
    framework: "CAMBRIDGE",
    subject: "Mathematics",
    gradeLabel: "IGCSE",
    standardCode: "0607",
    type: "MCQ",
    prompt: "What is the value of 2⁻³?",
    points: 1,
    options: {
      choices: [
        { id: "a", text: "−8", correct: false },
        { id: "b", text: "1/8", correct: true },
        { id: "c", text: "8", correct: false },
        { id: "d", text: "−1/8", correct: false },
      ],
    },
  },
  {
    organizationId: null,
    framework: "CAMBRIDGE",
    subject: "Mathematics",
    gradeLabel: "A Level",
    standardCode: "P1-2",
    type: "SHORT_ANSWER",
    prompt: "What is the sum of the interior angles of a triangle, in degrees?",
    points: 1,
    correctAnswer: "180",
  },
  {
    organizationId: null,
    framework: "CAMBRIDGE",
    subject: "Physics",
    gradeLabel: "IGCSE",
    standardCode: "0625",
    type: "TRUE_FALSE",
    prompt: "Sound waves are longitudinal waves.",
    points: 1,
    correctAnswer: "true",
  },
  {
    organizationId: null,
    framework: "CAMBRIDGE",
    subject: "Chemistry",
    gradeLabel: "A Level",
    standardCode: "AS-3",
    type: "LONG_ANSWER",
    prompt: "Describe one difference between ionic and covalent bonding in two sentences.",
    points: 2,
    markingScheme:
      "2 pts: clear contrast (e.g. electron transfer vs sharing). 1 pt: mentions only one type well. 0: incorrect.",
  },
  {
    organizationId: null,
    framework: "CAMBRIDGE",
    subject: "English",
    gradeLabel: "IGCSE",
    standardCode: "0500",
    type: "MCQ",
    prompt: "Which sentence uses the past perfect tense?",
    points: 1,
    options: {
      choices: [
        { id: "a", text: "She walks to school.", correct: false },
        { id: "b", text: "She had finished before noon.", correct: true },
        { id: "c", text: "She will finish soon.", correct: false },
        { id: "d", text: "She is finishing now.", correct: false },
      ],
    },
  },
  {
    organizationId: null,
    framework: "CAMBRIDGE",
    subject: "Biology",
    gradeLabel: "IGCSE",
    standardCode: "0610",
    type: "DRAG_DROP",
    prompt: "Match each term to the correct definition slot.",
    points: 2,
    questionSchema: {
      dragDrop: {
        targets: [
          { id: "t1", label: "Cell powerhouse" },
          { id: "t2", label: "Controls what enters the cell" },
        ],
        bank: [
          { id: "b1", text: "Mitochondrion" },
          { id: "b2", text: "Cell membrane" },
          { id: "b3", text: "Ribosome" },
        ],
        correct: { t1: "b1", t2: "b2" },
      },
    },
  },
  {
    organizationId: null,
    framework: "AP",
    subject: "Calculus AB",
    gradeLabel: "Grade 11–12",
    standardCode: "CHA-3",
    type: "MCQ",
    prompt: "What is the derivative of sin(x) with respect to x?",
    points: 1,
    options: {
      choices: [
        { id: "a", text: "cos(x)", correct: true },
        { id: "b", text: "−cos(x)", correct: false },
        { id: "c", text: "sin(x)", correct: false },
        { id: "d", text: "−sin(x)", correct: false },
      ],
    },
  },
  {
    organizationId: null,
    framework: "AP",
    subject: "Calculus AB",
    gradeLabel: "Grade 11–12",
    standardCode: "LIM-4",
    type: "SHORT_ANSWER",
    prompt: "Evaluate the limit as x approaches 0 of (sin x)/x.",
    points: 1,
    correctAnswer: "1",
  },
  {
    organizationId: null,
    framework: "AP",
    subject: "US History",
    gradeLabel: "Grade 11",
    standardCode: "NAT-1.0",
    type: "TRUE_FALSE",
    prompt: "The Declaration of Independence was adopted in 1776.",
    points: 1,
    correctAnswer: "true",
  },
  {
    organizationId: null,
    framework: "AP",
    subject: "US History",
    gradeLabel: "Grade 11",
    standardCode: "POL-2.0",
    type: "LONG_ANSWER",
    prompt: "In one paragraph, explain checks and balances with one example.",
    points: 3,
    markingScheme:
      "3 pts: defines separation + example (e.g. veto, judicial review). 2 pts: partial. 0–1: vague or wrong.",
  },
  {
    organizationId: null,
    framework: "AP",
    subject: "Computer Science A",
    gradeLabel: "Grade 10–12",
    standardCode: "MOD-2",
    type: "MCQ",
    prompt: "Which Java keyword declares a class cannot be subclassed?",
    points: 1,
    options: {
      choices: [
        { id: "a", text: "static", correct: false },
        { id: "b", text: "final", correct: true },
        { id: "c", text: "abstract", correct: false },
        { id: "d", text: "private", correct: false },
      ],
    },
  },
  {
    organizationId: null,
    framework: "AP",
    subject: "Biology",
    gradeLabel: "Grade 10–12",
    standardCode: "IST-1",
    type: "MCQ",
    prompt: "Which organelle contains DNA in a eukaryotic cell?",
    points: 1,
    options: {
      choices: [
        { id: "a", text: "Mitochondrion", correct: false },
        { id: "b", text: "Nucleus", correct: true },
        { id: "c", text: "Golgi apparatus", correct: false },
        { id: "d", text: "Lysosome", correct: false },
      ],
    },
  },
  {
    organizationId: null,
    framework: "AP",
    subject: "English Language",
    gradeLabel: "Grade 11",
    standardCode: "CLE-1",
    type: "MCQ",
    prompt: "Which best describes the role of a thesis statement?",
    points: 1,
    options: {
      choices: [
        { id: "a", text: "To list every source you will cite", correct: false },
        { id: "b", text: "To state the main claim or position of the essay", correct: true },
        { id: "c", text: "To summarize the conclusion only", correct: false },
        { id: "d", text: "To replace the need for body paragraphs", correct: false },
      ],
    },
  },
];
